### ISSUE TITLE
Example on K8s not working

### ISSUE THREAD

**Issue by chenele** [cloudflare/ebpf_exporter#287]
Hi

Trying to run the examples on local K8s cluster with the following simple spec:
```
apiVersion: v1
kind: Service
metadata:
  name: metrics-test
  labels:
    app.kubernetes.io/name: metrics-test
spec: 
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: metrics-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-test
  labels:
    app.kubernetes.io/name: metrics-test
spec:  
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metrics-test
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name:metrics-test
          image: ebpf_examples
          imagePullPolicy: Never
          securityContext:
            privileged: true
            runAsUser: 0
          args:
            - --config.dir
            - examples
            - --config.names
            - timers         
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP  
```

I see the following error: 
`Error attaching exporter: error loading bpf object from "examples/timers.bpf.o" for config "timers": failed to load BPF object: no such process`

Image was built with `docker build --tag ebpf_exmample --target ebpf_exporter_with_examples .`
any idea?
