### ISSUE TITLE
Option to easily discard bytes explicitely without label

### ISSUE THREAD

**Issue by aibor** [cloudflare/ebpf_exporter#369]
As described in the documentation, padding bytes in the counter key struct need to be considered when decoding the values.
The documentation suggests just to include the padding space in the previous value.

In case the structure is not as simple, it can get tricky and I need to define "reserved" fields. Those end up as label unnecessarily.

So, in order to avoid that, with a "discard" decoder I could explicitely discard such padding bytes.

I'd be happy to provide a patch, if you like the idea. Regarding the naming of  such a decoder I'm open to suggestions.

Edit: It seems better to just add a simple "discard" or "skip" config flag to the label.

**Comment by bobrik** [comment]
Do you have an example struct that requires this? If we want to have this functionality, it needs an example attached.

**Comment by aibor** [comment]
Right now I have a struct like this:

```
struct inet_frags_counter_key_t {
  u32 ifindex;
  u8 ip_version;
  u8 ip_protocol;
};
```

Due to alignment, it is 8 byte long. In the config, I can't use `size: 3` for the label ip_protocol, because it is an invalid length. So I need to use a config like this:

```
metrics:
  counters:
    - name: frags_total
      help: number of fragments seen
      labels: 
        - name: interface
          size: 4
          decoders:
            - name: ifname
        - name: ip_version
          size: 1
          decoders:
            - name: uint
        - name: ip_protocol
          size: 1
          decoders:
            - name: uint
        - name: padding_bytes
          size: 2
          decoders:
            - name: uint
```

The label "padding_bytes" is added just to get the proper map key size.

In order to avoid the unnecessary label, an additional config key (e.g. `discard: true`) might be a straight forward solution?
So, the config would look like this:

```
metrics:
  counters:
    - name: frags_total
      help: number of fragments seen
      labels:
        - name: interface
          size: 4
          decoders:
            - name: ifname
        - name: ip_version
          size: 1
          decoders:
            - name: uint
        - name: ip_protocol
          size: 1
          decoders:
            - name: uint
        - size: 2
          discard: true
```
