### ISSUE TITLE
metrics not exporterd on BPF_PERF_OUTPUT

### ISSUE THREAD

**Issue by luginbash** [cloudflare/ebpf_exporter#46]
Hello,

I was in need of a tcpconnlat exporter, but wasn't able to find one in the `examples/`. So I tried to translate the tcpconnlat.py, it compiled eventually, but not exporting any useful data.

config.yaml:
```yaml
programs:
  - name: tcpconnlat
    metrics:
      counters:
        - name: data4
          help: tcp4 connection latency
          table: ipv4_events
          labels:
            - name: time
              size: 64
              decoders:
                - name: uint
            - name: pid
              size: 32
              decoders:
                - name: uint
            - name: source_addr
              size: 32
              decoders:
                - name: uint
            - name: dst_addr
              size: 32
              decoders:
                - name: uint
            - name: ip_addr
              size: 64
              decoders:
                - name: uint
            - name: dst_port
              size: 16
              decoders:
                - name: uint
            - name: delt_us
              size: 64
              decoders:
                - name: uint
            - name: proc_name
              size: 16
              decoders:
                - name: string
        - name: data6
          help: tcp6 connection latency
          table: ipv6_events
          labels:
            - name: time
              size: 64
              decoders:
                - name: uint
            - name: pid
              size: 32
              decoders:
                - name: uint
            - name: source_addr
              size: 128
              decoders:
                - name: uint
            - name: dst_addr
              size: 128
              decoders:
                - name: uint
            - name: ip_addr
              size: 64
              decoders:
                - name: uint
            - name: dst_port
              size: 16
              decoders:
                - name: uint
            - name: delt_us
              size: 64
              decoders:
                - name: uint
            - name: proc_name
              size: 16
              decoders:
                - name: string
    kprobes:
      tcp_rcv_state_process: trace_tcp_rcv_state_process
      tcp_v4_connect: trace_connect
      tcp_v6_connect: trace_connect
    code: |
      #include <uapi/linux/ptrace.h>
      #include <net/sock.h>
      #include <net/tcp_states.h>
      #include <bcc/proto.h>
      struct info_t {
          u64 ts;
          u32 pid;
          char task[TASK_COMM_LEN];
      };
      BPF_HASH(start, struct sock *, struct info_t);
      // separate data structs for ipv4 and ipv6
      struct ipv4_data_t {
          u64 ts_us;
          u32 pid;
          u32 saddr;
          u32 daddr;
          u64 ip;
          u16 dport;
          u64 delta_us;
          char task[TASK_COMM_LEN];
      };
      BPF_PERF_OUTPUT(ipv4_events);
      struct ipv6_data_t {
          u64 ts_us;
          u32 pid;
          unsigned __int128 saddr;
          unsigned __int128 daddr;
          u64 ip;
          u16 dport;
          u64 delta_us;
          char task[TASK_COMM_LEN];
      };
      BPF_PERF_OUTPUT(ipv6_events);
      int trace_connect(struct pt_regs *ctx, struct sock *sk)
      {
          u32 pid = bpf_get_current_pid_tgid();
          struct info_t info = {.pid = pid};
          info.ts = bpf_ktime_get_ns();
          bpf_get_current_comm(&info.task, sizeof(info.task));
          start.update(&sk, &info);
          return 0;
      };
      // See tcp_v4_do_rcv() and tcp_v6_do_rcv(). So TCP_ESTBALISHED and TCP_LISTEN
      // are fast path and processed elsewhere, and leftovers are processed by
      // tcp_rcv_state_process(). We can trace this for handshake completion.
      // This should all be switched to static tracepoints when available.
      int trace_tcp_rcv_state_process(struct pt_regs *ctx, struct sock *skp)
      {
          // will be in TCP_SYN_SENT for handshake
          if (skp->__sk_common.skc_state != TCP_SYN_SENT)
              return 0;
          // check start and calculate delta
          struct info_t *infop = start.lookup(&skp);
          if (infop == 0) {
              return 0;   // missed entry or filtered
          }
          u64 ts = infop->ts;
          u64 now = bpf_ktime_get_ns();
          u64 delta_us = (now - ts) / 1000ul;
      #ifdef MIN_LATENCY
          if ( delta_us < DURATION_US ) {
              return 0; // connect latency is below latency filter minimum
          }
      #endif
          // pull in details
          u16 family = 0, dport = 0;
          family = skp->__sk_common.skc_family;
          dport = skp->__sk_common.skc_dport;
          // emit to appropriate data path
          if (family == AF_INET) {
              struct ipv4_data_t data4 = {.pid = infop->pid, .ip = 4};
              data4.ts_us = now / 1000;
              data4.saddr = skp->__sk_common.skc_rcv_saddr;
              data4.daddr = skp->__sk_common.skc_daddr;
              data4.dport = ntohs(dport);
              data4.delta_us = delta_us;
              __builtin_memcpy(&data4.task, infop->task, sizeof(data4.task));
              ipv4_events.perf_submit(ctx, &data4, sizeof(data4));
          } else /* AF_INET6 */ {
              struct ipv6_data_t data6 = {.pid = infop->pid, .ip = 6};
              data6.ts_us = now / 1000;
              bpf_probe_read(&data6.saddr, sizeof(data6.saddr),
                  skp->__sk_common.skc_v6_rcv_saddr.in6_u.u6_addr32);
              bpf_probe_read(&data6.daddr, sizeof(data6.daddr),
                  skp->__sk_common.skc_v6_daddr.in6_u.u6_addr32);
              data6.dport = ntohs(dport);
              data6.delta_us = delta_us;
              __builtin_memcpy(&data6.task, infop->task, sizeof(data6.task));
              ipv6_events.perf_submit(ctx, &data6, sizeof(data6));
          }
          start.delete(&skp);
          return 0;
      }
```

output:
```
# HELP ebpf_exporter_ebpf_programs Info about ebpf programs
# TYPE ebpf_exporter_ebpf_programs gauge
ebpf_exporter_ebpf_programs{function="trace_connect",program="tcpconnlat",tag="4bfdfb7f1304f9c5"} 1
ebpf_exporter_ebpf_programs{function="trace_tcp_rcv_state_process",program="tcpconnlat",tag="8c233b2f38e959ca"} 1
# HELP ebpf_exporter_enabled_programs The set of enabled programs
# TYPE ebpf_exporter_enabled_programs gauge
ebpf_exporter_enabled_programs{name="tcpconnlat"} 1
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 6
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 740112
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 740112
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 2800
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 334
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 2.234368e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 740112
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 6.5470464e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 1.31072e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 3517
# HELP go_memstats_heap_released_bytes_total Total number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes_total counter
go_memstats_heap_released_bytes_total 0
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 6.6781184e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 0
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 3851
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 1728
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 17328
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 32768
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.473924e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 531728
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 327680
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 327680
# HELP go_memstats_sys_bytes Number of bytes obtained by system. Sum of all system allocations.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 6.9926912e+07
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 2.25
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 16
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.18468608e+08
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.54831637837e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 5.64097024e+08
```
